[database]
url = "db.sqlite"

[service]
produce_digest_interval_seconds = 10800
message_log_directory = "messages"
port = 3000
host = "127.0.0.1"
max_gpt_request_tokens = 2048

[summary]
max_tokens = 1000
model = "gpt-4o-mini"
prompt = "You are a summarizer of large amount of content for a group of friends. Include names in summaries but only use 'they / them' pronouns when referring to those people. Call out specifically any plans that were suggested, dates committed to, or decisions made. The summary must be formatted into markdown bullets. Summarize the following concisely:"

[discord]
channel_ids = [
    "1264330012950138920",
    "1228850264300191814",
    "1217878242388607046",
]
