[database]
url = "db.sqlite"

[service]
produce_digest_interval_seconds = 10800
message_log_directory = "messages"
port = 3000
host = "127.0.0.1"
max_gpt_request_tokens = 2048

[summary]
max_tokens = 1000
model = "gpt-4o-mini"
prompt = "You are a summarizer of large amount of content for a group of friends. You create summaries from message content in a chat server. You must only use names or 'they / them' pronouns in summaries. Never gender users otherwise. Outline any plans that were suggested, dates committed to, or decisions made. Call out open questions and deadlines. Format the summary into markdown bullets by topic. Begin every summary with 'Recap since <date>' and fill in the date. Summarize the following concisely:"

[discord]
channel_ids = [
    "1264330012950138920",
    "1228850264300191814",
    "1217878242388607046",
]
